// refactored/src/components/home/EventsSection.vue
<script setup lang="ts">
import { useContent } from '@/composables/useContent'
const { events, isLoadingEvents } = useContent()
</script>

<template>
	<section id="events" class="py-20" style="background: var(--color-vintage-cream)">
		<div class="container mx-auto px-4">
			<div class="flex items-center justify-center gap-3 mb-12">
				<span class="w-8 h-8 rounded-full inline-block" style="background: var(--color-vintage-tan)"></span>
				<h2 class="groovy-title text-5xl" style="color: var(--color-vintage-dark)">Events</h2>
			</div>

			<div v-if="isLoadingEvents" class="text-center text-xl opacity-80">Loading events...</div>

			<div v-else class="max-w-3xl mx-auto space-y-6">
				<div v-for="event in events" :key="event.id" class="p-6 rounded-lg border" style="border-color: var(--color-vintage-brown)">
					<h3 class="text-2xl font-serif mb-1" style="color: var(--color-vintage-dark)">{{ event.title }}</h3>
					<p v-if="event.description" class="mb-2" style="color: var(--color-vintage-dark)">{{ event.description }}</p>
					<div v-if="event.event_date" class="opacity-80">
						{{ new Date(event.event_date).toLocaleString() }}
					</div>
				</div>
			</div>
		</div>
	</section>
</template>

// components/events-section.tsx
"use client"

import { Calendar } from "lucide-react"
import { useContent } from "@/lib/content-context"

export function EventsSection() {
  const { events, isLoadingEvents } = useContent()

  if (isLoadingEvents) {
    return (
      <section id="events" className="py-20 bg-vintage-cream">
        <div className="container mx-auto px-4 text-center">
          <div className="text-vintage-dark text-xl">Loading events...</div>
        </div>
      </section>
    )
  }
  return (
    <section id="events" className="py-20 bg-vintage-cream">
      <div className="container mx-auto px-4">
        <div className="flex items-center justify-center gap-3 mb-12">
          <Calendar className="w-8 h-8 text-vintage-tan" />
          <h2 className="groovy-title text-5xl text-vintage-dark">Events</h2>
        </div>

        <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-6">
          {events.map((event) => (
            <div
              key={event.id}
              className="bg-vintage-tan/20 border-2 border-vintage-brown p-6 rounded-lg hover:shadow-xl transition-shadow"
            >
              <h3 className="text-2xl font-serif text-vintage-dark mb-2">{event.title}</h3>
              <p className="text-vintage-brown mb-4">{event.description}</p>
              <div className="flex items-center gap-2 text-sm text-vintage-dark">
                <Calendar className="w-4 h-4" />
                <time dateTime={event.event_date}>
                  {new Date(event.event_date).toLocaleDateString("en-US", {
                    weekday: "long",
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </time>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
