// refactored/src/components/home/VideosSection.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useContent } from '@/composables/useContent'
const { videos, isLoadingVideos } = useContent()
const getYouTubeEmbedUrl = (url: string) => {
	const id = url.split('v=')[1]?.split('&')[0]
	return `https://www.youtube.com/embed/${id}`
}
</script>

<template>
	<section id="videos" class="py-20" style="background: var(--color-vintage-dark)">
		<div class="container mx-auto px-4">
			<div class="flex items-center justify-center gap-3 mb-12">
				<span class="w-8 h-8 rounded-full inline-block" style="background: var(--color-vintage-tan)"></span>
				<h2 class="groovy-title text-5xl" style="color: var(--color-vintage-cream)">Videos</h2>
			</div>

			<div v-if="isLoadingVideos" class="text-center text-xl" style="color: var(--color-vintage-cream)">Loading videos...</div>

			<div v-else class="max-w-4xl mx-auto space-y-8">
				<div v-for="video in videos" :key="video.id" class="rounded-lg p-6" style="background: color-mix(in oklab, var(--color-vintage-cream) 10%, transparent)">
					<h3 class="text-2xl font-serif mb-4 underline decoration-2 underline-offset-4" style="color: var(--color-vintage-cream); text-decoration-color: var(--color-vintage-tan)">
						{{ video.title }}
					</h3>
					<div class="aspect-video rounded overflow-hidden">
						<iframe
							width="100%"
							height="100%"
							:src="getYouTubeEmbedUrl(video.youtube_url)"
							:title="video.title"
							allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
							allowfullscreen
							class="w-full h-full"
						/>
					</div>
				</div>
			</div>
		</div>
	</section>
</template>

// components/videos-section.tsx
"use client"

import { Video } from "lucide-react"
import { useContent } from "@/lib/content-context"

function getYouTubeEmbedUrl(url: string) {
  const videoId = url.split("v=")[1]?.split("&")[0]
  return `https://www.youtube.com/embed/${videoId}`
}

export function VideosSection() {
  const { videos, isLoadingVideos } = useContent()

  if (isLoadingVideos) {
    return (
      <section id="videos" className="py-20 bg-vintage-dark">
        <div className="container mx-auto px-4 text-center">
          <div className="text-vintage-cream text-xl">Loading videos...</div>
        </div>
      </section>
    )
  }
  return (
    <section id="videos" className="py-20 bg-vintage-dark">
      <div className="container mx-auto px-4">
        <div className="flex items-center justify-center gap-3 mb-12">
          <Video className="w-8 h-8 text-vintage-tan" />
          <h2 className="groovy-title text-5xl text-vintage-cream">Videos</h2>
        </div>

        <div className="max-w-4xl mx-auto space-y-8">
          {videos.map((video) => (
            <div key={video.id} className="bg-vintage-cream/10 p-6 rounded-lg">
              <h3 className="text-2xl font-serif text-vintage-cream mb-4 underline decoration-vintage-tan decoration-2 underline-offset-4">
                {video.title}
              </h3>
              <div className="aspect-video rounded overflow-hidden">
                <iframe
                  width="100%"
                  height="100%"
                  src={getYouTubeEmbedUrl(video.youtube_url)}
                  title={video.title}
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                  className="w-full h-full"
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
